spring:
  profiles:
    active:
    - dev
---

spring:
  profiles: dev
  application:
    name: microservicecloud-config-client1

---

spring:
  profiles: test
  application:
    name: microservicecloud-config-client2

